# Generated by Django 5.2.6 on 2025-09-10 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0002_alter_autor_fecha_nacimiento_and_more'),
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autor.autor'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
