# Generated by Django 5.2.6 on 2025-09-16 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0003_alter_autor_nacionalidad'),
        ('libro', '0002_libro_autor_alter_libro_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autor.autor'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
